/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 FoodTruck.gltf --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function FoodTruck(props) {
    const { nodes, materials } = useGLTF("/FoodTruck-transformed.glb");
    return (
        <group {...props} dispose={null}>
            <group position={[-0.1, -5.37, 0.59]} rotation={[-Math.PI / 2, 0, 0]} scale={0.16}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <mesh
                        geometry={nodes.Cube_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[0, 1958.83, -79.34]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 123.78, 100]}
                    />
                    <mesh
                        geometry={nodes.Cube003_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[-1002.49, 1936.9, 1090.26]}
                        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                        scale={[35.39, 43.81, 35.39]}
                    />
                    <mesh geometry={nodes.Cube008_Material001_0.geometry} material={materials["Material.001"]} position={[98.65, 5357.47, -79.34]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <mesh
                        geometry={nodes.Cube010_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[2169.24, 4653.02, 674.92]}
                        rotation={[Math.PI / 2, 0.38, Math.PI]}
                        scale={[61.7, 37.71, 896.45]}
                    />
                    <mesh
                        geometry={nodes.Cube013_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[470.88, 3045.43, 462.61]}
                        rotation={[-Math.PI / 2, 0, -0.72]}
                        scale={[480.43, 294.24, 29.97]}
                    />
                    <mesh
                        geometry={nodes.Cube014_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[-884.84, 4449.26, -577.91]}
                        rotation={[-Math.PI / 2, 0.46, -0.74]}
                        scale={[31.92, 31.92, 327.27]}
                    />
                    <mesh geometry={nodes.Cube015_Material001_0.geometry} material={materials["Material.001"]} position={[569.3, 5685.39, 16.69]} rotation={[-Math.PI / 2, 0, -0.43]} scale={100} />
                    <mesh
                        geometry={nodes.Cube016_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[414.68, 5579.88, 358.2]}
                        rotation={[-Math.PI / 2, 0, -0.43]}
                        scale={[260.61, 13.46, 41.23]}
                    />
                    <mesh
                        geometry={nodes.Cube017_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[-2742.65, 3085.89, 7.28]}
                        rotation={[-Math.PI / 2, 1.37, 0.25]}
                        scale={[273.22, 273.22, 71.5]}
                    />
                    <mesh
                        geometry={nodes.Cube018_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[1498.32, 5621.64, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[177.6, 177.6, 228.18]}
                    />
                    <mesh geometry={nodes.Cube019_Material001_0.geometry} material={materials["Material.001"]} position={[-572.08, 5928.96, 246.09]} rotation={[-Math.PI / 2, 0, -0.3]} scale={100} />
                    <mesh geometry={nodes.Cube020_Material001_0.geometry} material={materials["Material.001"]} position={[588.42, 3296.35, -109.4]} rotation={[-1.9, 0, -0.55]} scale={224.65} />
                    <mesh
                        geometry={nodes.Cube021_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[248.58, 3106.25, 338.77]}
                        rotation={[-1.49, 0, 0.96]}
                        scale={[333.93, 21.27, 18.37]}
                    />
                    <mesh
                        geometry={nodes.Cube023_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[25.32, 2252.8, 917.14]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[127.19, 84.92, 84.92]}
                    />
                    <mesh geometry={nodes.Cylinder_Material001_0.geometry} material={materials["Material.001"]} position={[-2929.66, 3792.44, 545.14]} scale={[112.69, 112.69, 139.48]} />
                    <mesh
                        geometry={nodes.Cylinder001_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[-472.19, 3351.5, 298.28]}
                        rotation={[-Math.PI / 2, 0, -0.93]}
                        scale={[285.2, 286.17, 201.24]}
                    />
                    <mesh
                        geometry={nodes.Cylinder002_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[-464.66, 3137.88, 329.69]}
                        rotation={[-Math.PI / 2, 0, -0.24]}
                        scale={[143.9, 143.9, 8.02]}
                    />
                    <mesh
                        geometry={nodes.Cylinder010_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[-275.15, 2927.01, 924.27]}
                        rotation={[-0.31, 0, 3.14]}
                        scale={[51.47, 51.47, 32.15]}
                    />
                    <mesh
                        geometry={nodes.Cylinder012_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[1401.35, 5329.87, 447.79]}
                        rotation={[0.28, 0, 0]}
                        scale={[36.5, 36.99, 122.52]}
                    />
                    <mesh
                        geometry={nodes.Cylinder019_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[-1012.47, 3567.78, -489.66]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[270.99, 270.99, 400.83]}
                    />
                    <mesh geometry={nodes.Cylinder020_Material001_0.geometry} material={materials["Material.001"]} position={[1606.87, 4065.33, 48.35]} rotation={[0, -0.4, -2.88]} scale={88.07} />
                    <mesh
                        geometry={nodes.Cylinder022_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[523.72, 4287.6, 556.96]}
                        rotation={[-Math.PI / 2, -0.82, 0.26]}
                        scale={[136.26, 136.26, 165.04]}
                    />
                    <mesh
                        geometry={nodes.Cylinder023_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[28.24, 4660.59, 580.73]}
                        rotation={[-0.94, 0.57, 2.47]}
                        scale={[136.26, 136.26, 165.04]}
                    />
                    <mesh
                        geometry={nodes.Cylinder024_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[1105.68, 4398.85, 518.91]}
                        rotation={[-0.89, 0.5, 2.36]}
                        scale={[136.26, 136.26, 165.04]}
                    />
                    <mesh
                        geometry={nodes.Cylinder025_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[-146.53, 5501.87, -243.11]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[294.44, 294.44, 90.49]}
                    />
                    <mesh geometry={nodes.NurbsPath_Material001_0.geometry} material={materials["Material.001"]} position={[0, 4422.68, 487.84]} rotation={[-Math.PI / 2, 0, 0]} scale={716.78} />
                    <mesh
                        geometry={nodes.Sphere_Material001_0.geometry}
                        material={materials["Material.001"]}
                        position={[624.18, 3866.03, -155.87]}
                        rotation={[-Math.PI / 2, 0, -2.35]}
                        scale={189.48}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/FoodTruck-transformed.glb");
