/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 meditation.gltf --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Meditation(props) {
    const { nodes, materials } = useGLTF("/meditation-transformed.glb");
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Cylinder.geometry} material={materials["Material.002"]} position={[0.94, 1.41, 0.88]} />
            <mesh geometry={nodes.Cylinder005.geometry} material={materials["Material.002"]} position={[0.94, 1.41, -0.9]} />
            <mesh geometry={nodes.Cylinder002.geometry} material={materials["Material.001"]} position={[0.94, 0.43, 0.88]} />
            <mesh geometry={nodes.Cylinder004.geometry} material={materials["Material.001"]} position={[0.94, 0.43, -0.9]} />
            <mesh geometry={nodes.Circle001.geometry} material={materials["Material.012"]} position={[-1.24, 0.21, 0.49]} />
            <mesh geometry={nodes.Circle002.geometry} material={materials["Material.012"]} position={[-1.24, 0.21, -0.5]} />
            <mesh geometry={nodes.Circle.geometry} material={materials["Material.006"]} position={[-0.54, -0.34, 0]} />
            <mesh geometry={nodes.Curve004.geometry} material={materials["Material.002"]} position={[1.34, 0.92, 0.78]} />
            <mesh geometry={nodes.Curve002.geometry} material={materials["Material.002"]} position={[1.34, 0.92, -0.76]} />
            <mesh geometry={nodes.Curve005.geometry} material={materials["Material.001"]} position={[0.54, 0.92, 0.78]} />
            <mesh geometry={nodes.Curve001.geometry} material={materials["Material.001"]} position={[0.54, 0.92, -0.76]} />
            <mesh geometry={nodes.Sphere001.geometry} material={materials["Material.012"]} position={[-1.29, -0.84, 0.48]} />
            <mesh geometry={nodes.Cylinder001.geometry} material={materials["Material.003"]} position={[0.93, 0.94, 0.6]} />
            <mesh geometry={nodes.Sphere002.geometry} material={materials["Material.012"]} position={[-1.29, -0.84, -0.47]} />
            <mesh geometry={nodes.Cylinder003.geometry} material={materials["Material.003"]} position={[0.93, 0.94, -0.58]} />
        </group>
    );
}

useGLTF.preload("/meditation-transformed.glb");
