/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function SplineBall({ ...props }) {
    const { nodes, materials } = useSpline("https://prod.spline.design/TIO9gA3fMCnofVsC/scene.splinecode");
    return (
        <>
            {/* <color attach="background" args={[""]} /> */}
            <group {...props} dispose={null}>
                <directionalLight
                    name="Directional Light 2"
                    castShadow
                    intensity={1}
                    shadow-mapSize-width={1024}
                    shadow-mapSize-height={1024}
                    shadow-camera-near={-10000}
                    shadow-camera-far={100000}
                    shadow-camera-left={-1000}
                    shadow-camera-right={1000}
                    shadow-camera-top={1000}
                    shadow-camera-bottom={-1000}
                    position={[-541.34, 535.19, 1667.09]}
                />
                <pointLight
                    name="Point Light"
                    castShadow
                    intensity={1.61}
                    distance={2000}
                    shadow-mapSize-width={1024}
                    shadow-mapSize-height={1024}
                    shadow-camera-near={100}
                    shadow-camera-far={100000}
                    position={[-982.21, -315.78, -719.74]}
                />
                <mesh name="Sphere 2" geometry={nodes["Sphere 2"].geometry} material={materials.Glass} castShadow receiveShadow position={[-61.77, 325.89, 232.25]} rotation={[0, 0, 0.04]} />
                <mesh
                    name="Sphere 9"
                    geometry={nodes["Sphere 9"].geometry}
                    material={materials.Glass}
                    castShadow
                    receiveShadow
                    position={[261.5, 71.32, 495.78]}
                    rotation={[-Math.PI, 1.57, -Math.PI]}
                />
                <mesh
                    name="Sphere 3"
                    geometry={nodes["Sphere 3"].geometry}
                    material={materials.Glass}
                    castShadow
                    receiveShadow
                    position={[205.85, -324.68, 244.05]}
                    rotation={[-Math.PI, 1.57, -Math.PI]}
                />
                <mesh name="Sphere 7" geometry={nodes["Sphere 7"].geometry} material={materials.Blue} castShadow receiveShadow position={[76.02, 456.37, -125.24]} />
                <mesh name="Sphere 6" geometry={nodes["Sphere 6"].geometry} material={materials.Blue} castShadow receiveShadow position={[-89.98, -321.63, -125.24]} />
                <mesh name="Sphere 8" geometry={nodes["Sphere 8"].geometry} material={materials.white} castShadow receiveShadow position={[262.02, -247.63, -363.24]} />
                <mesh name="Sphere 5" geometry={nodes["Sphere 5"].geometry} material={materials.white} castShadow receiveShadow position={[-152.98, 246.37, -363.24]} />
                <mesh name="Sphere 4" geometry={nodes["Sphere 4"].geometry} material={materials.white} castShadow receiveShadow position={[18.02, 83.37, -363.24]} />
                <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials.Glass} castShadow receiveShadow position={[-119.5, -113.5, -51.27]} />
                <directionalLight
                    name="Directional Light"
                    castShadow
                    intensity={0.7}
                    shadow-mapSize-width={1024}
                    shadow-mapSize-height={1024}
                    shadow-camera-near={-10000}
                    shadow-camera-far={100000}
                    shadow-camera-left={-1000}
                    shadow-camera-right={1000}
                    shadow-camera-top={1000}
                    shadow-camera-bottom={-1000}
                    position={[200, 300, 300]}
                />
                <OrthographicCamera name="1" makeDefault={true} zoom={0.6} far={100000} near={-100000} position={[192.9, -69.54, 1000]} rotation={[0, 0, 0]} />
                <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
            </group>
        </>
    );
}
