/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 dumbbell.gltf --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Dumbbell(props) {
    const { nodes, materials } = useGLTF("/dumbbell-transformed1.glb");
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Sphere012.geometry} material={materials.A2} position={[-1.18, 1.27, 1.14]} rotation={[-0.89, 0.93, 0]} scale={1.16} />
        </group>
    );
}

useGLTF.preload("/dumbbell-transformed1.glb");
